In [9]:
import numpy as np

In [285]:
class Cube:
    def __init__(self):
        self.cube = np.zeros((6, 3, 3)).astype(object)
        self.colors = ['W', 'G', 'Y', 'B', 'R', 'O']
        for i, c in enumerate(self.colors):
            self.cube[i] = c
        
        self.front = self.cube[0]
        self.up = self.cube[1]
        self.back = self.cube[2]
        self.down = self.cube[3]
        self.left = self.cube[4]
        self.right = self.cube[5]
    
    def __getitem__(self, key):
        return getattr(self, key)
    
    def rotate_u(self):
        # Performing an U: Up and the bottom are not changed
        self.up = np.rot90(self.up, k=3)
        self.down = self.down
        temp = self.front.copy()
        self.front[0] = self.right[0]
        self.right[0] = self.back[0]
        self.back[0] = self.left[0]
        self.left[0] = temp[0]
        return self.__repr__()
    
    def __str__(self):
        return self.cube.__str__()
    
    def __repr__(self):
        return self.cube.__repr__()

In [286]:
cube = Cube()
cube

array([[['W', 'W', 'W'],
        ['W', 'W', 'W'],
        ['W', 'W', 'W']],

       [['G', 'G', 'G'],
        ['G', 'G', 'G'],
        ['G', 'G', 'G']],

       [['Y', 'Y', 'Y'],
        ['Y', 'Y', 'Y'],
        ['Y', 'Y', 'Y']],

       [['B', 'B', 'B'],
        ['B', 'B', 'B'],
        ['B', 'B', 'B']],

       [['R', 'R', 'R'],
        ['R', 'R', 'R'],
        ['R', 'R', 'R']],

       [['O', 'O', 'O'],
        ['O', 'O', 'O'],
        ['O', 'O', 'O']]], dtype=object)

In [290]:
print(cube.rotate_u())

array([[['W', 'W', 'W'],
        ['W', 'W', 'W'],
        ['W', 'W', 'W']],

       [['G', 'G', 'G'],
        ['G', 'G', 'G'],
        ['G', 'G', 'G']],

       [['Y', 'Y', 'Y'],
        ['Y', 'Y', 'Y'],
        ['Y', 'Y', 'Y']],

       [['B', 'B', 'B'],
        ['B', 'B', 'B'],
        ['B', 'B', 'B']],

       [['R', 'R', 'R'],
        ['R', 'R', 'R'],
        ['R', 'R', 'R']],

       [['O', 'O', 'O'],
        ['O', 'O', 'O'],
        ['O', 'O', 'O']]], dtype=object)


In [256]:
cube = np.zeros((6, 3, 3)).astype(object)
colors = ['W', 'G', 'Y', 'B', 'R', 'O']
for i, c in enumerate(colors):
    cube[i] = c
front = cube[0]
up = cube[1]
back = cube[2]
down = cube[3]
left = cube[4]
right = cube[5]

# U

In [255]:
# Performing an U: Up and the bottom are not changed
up = np.rot90(up, k=3)
down = down
temp = front.copy()
front[0] = right[0]
right[0] = back[0]
back[0] = left[0]
left[0] = temp[0]

array([[['W', 'W', 'W'],
        ['W', 'W', 'W'],
        ['W', 'W', 'W']],

       [['G', 'G', 'G'],
        ['G', 'G', 'G'],
        ['G', 'G', 'G']],

       [['Y', 'Y', 'Y'],
        ['Y', 'Y', 'Y'],
        ['Y', 'Y', 'Y']],

       [['B', 'B', 'B'],
        ['B', 'B', 'B'],
        ['B', 'B', 'B']],

       [['R', 'R', 'R'],
        ['R', 'R', 'R'],
        ['R', 'R', 'R']],

       [['O', 'O', 'O'],
        ['O', 'O', 'O'],
        ['O', 'O', 'O']]], dtype=object)

# U'

In [242]:
# Performing an U: Up and the bottom are not changed
up = np.rot90(up)
down = down
temp = front.copy()
front[0] = left[0]
left[0] = back[0]
back[0] = right[0]
right[0] = temp[0]

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]],

       [[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]],

       [[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]],

       [[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]],

       [[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]]], dtype=object)

# D

In [217]:
# Performing an D: Up and the bottom are not changed
down = np.rot90(down)
up = up
temp = front.copy()
front[2] = left[2]
left[2] = back[2]
back[2] = right[2]
right[2] = temp[2]

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]],

       [[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]],

       [[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]],

       [[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]],

       [[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]]], dtype=object)

# D'

In [246]:
# Performing an D: Up and the bottom are not changed
down = np.rot90(down, k=3)
up = up
temp = front.copy()
front[2] = right[2]
right[2] = back[2]
back[2] = left[2]
left[2] = temp[2]

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]],

       [[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]],

       [[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]],

       [[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]],

       [[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]]], dtype=object)

In [220]:
x = np.arange(9).reshape(3, 3)+1

In [194]:
up = np.rot90(up, k=3)
down = down
temp = front.copy()
front[0] = right[0]
right[0] = back[0]
back[0] = left[0]
left[0] = temp[0]

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]],

       [[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]],

       [[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]],

       [[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]],

       [[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]]], dtype=object)

In [130]:
x = np.arange(9).reshape(3, 3)+1

In [152]:
np.rot90(x.T).T

array([[7, 4, 1],
       [8, 5, 2],
       [9, 6, 3]])

In [148]:
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]).T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
np.array([[1, 2, 1], [4, 5, 2], [7, 8, 3]])

In [146]:
np.roll(x.T, 2)

array([[6, 9, 1],
       [4, 7, 2],
       [5, 8, 3]])